# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

variables:
  sln: './GloonCompiler.sln'
  tests: './GloonCompiler.Tests/GloonCompiler.Tests.fsproj'

parameters:
- name:     operatingSystems
  type:     object
  default:
  - name:     Ubuntu
    vmImage:  ubuntu-latest
  - name:     Windows
    vmImage:  windows-latest
  - name:     macOS
    vmImage:  macOS-latest
- name:     configurations
  type:     object
  default:
  - Debug
  - Release

jobs:
- ${{ each c in parameters.configurations }}:
  - ${{ each os in parameters.operatingSystems }}:
    - job:  job${{ os.name }}${{ c }}
      displayName: ${{ c }} (${{ os.name }})
      pool:
        vmImage:  ${{ os.vmImage }}
      steps:
      - task: DotNetCoreCLI@2
        displayName: Build minsk (${{ os.name }} ${{ c }})
        inputs:
          command: build
          projects: $(sln)
          arguments: --configuration ${{ c }}
      - task: DotNetCoreCLI@2
        displayName: Run tests (${{ os.name }} ${{ c }})
        inputs:
          command: test
          projects: $(tests)
          arguments: --configuration ${{ c }}
          publishTestResults: true